import type { Metadata } from 'next'

import { AppProvider } from '@/components/providers/app-provider'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className="flex min-h-svh flex-col" suppressHydrationWarning>
        <AppProvider>
          <main className="flex flex-1 flex-col">{children}</main>
        </AppProvider>
      </body>
    </html>
  )
}
