import { queryClient } from '@/lib/react-query'
import { QueryClientProvider } from '@tanstack/react-query'
import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { Helmet, HelmetProvider } from 'react-helmet-async'

import { Toaster as SonnerToaster } from 'sonner'

import { ThemeProvider } from '../components/theme/theme-provider'
import { Toaster } from '../components/ui/toaster'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
              <body
                className="flex min-h-svh flex-col"
                suppressHydrationWarning
              >
                <main className="flex flex-1 flex-col">
                <SessionProvider>
                  <HelmetProvider>
                    <ThemeProvider storageKey="my-clinic-theme" defaultTheme="dark">
                      <Helmet titleTemplate="%s | xon.clinic" />
                      <SonnerToaster richColors />
                      <Toaster />
                      <QueryClientProvider client={queryClient}>
                            {

                          children
                          
                          }
                
            </QueryClientProvider>
          </ThemeProvider>
        </HelmetProvider>
      </SessionProvider>
                </main>
              </body>
    </html>
  )
}
